In [ ]:
# Hello! I am a test cell. You can run me to see if your Python environment is working.
# Try pressing 'Ctrl + Enter' and see if you can see the message below.

print("If it is working, it is working. If it is not, it is not.")

# Getting Started with Pandas

Pandas provides data structures and functions designed to make working with structured or tabular data intuitive and flexible. Moreover, it contains data structures and data manipulation tools intended to make data processing and analysis fast and convenient in Python.

It merges data manipulation capabilities found in spreadsheets and relational databases (such as SQL) with the power of Python. And it's really cool to work with.

**Pandas will be a major tool throughout this course! So, this is a very important notebook. You should become friends with this notebook and dream about it tonight.**

## The Dataset: Immigration to Canada from 1980 to 2013

Dataset source: https://www.un.org/development/desa/pd/data/international-migration-flows

In the same folder as this notebook, you will find a file called Canada.xlsx (check if you have it in the same folder locally on your machine).

The dataset contains annual data on international immigrants to Canada. We will explore it throughout this class :p

In [ ]:
# To get started with Pandas, we need to import the library.
# Pythonic people (cool people who work with Python) conventionally work with Pandas using the alias `pd`:

import pandas as pd

Did you encounter any problems running the code above? Is your code producing any errors? Don't worry. If you have seen this message:

```python
ModuleNotFoundError: No module named 'pandas'
```

You need to install the Pandas package. To do that, open a terminal, activate the Conda environment, and install the package with the following commands:

```bash
# First, activate the Conda environment
conda activate dm_web

# Then, install the package
pip install pandas
pip install pyarrow  # <--- a required dependency of Pandas in the next major release. By installing it now, you can avoid annoying warning messages.
```

After installing the package, you may need to restart the notebook (click the "Restart" button above). After that, try to execute the cell above again.

**Note: This error will appear with any new package you want to use and haven't installed. In such cases, you will need to install the packages using pip.**

In [ ]:
# Now, we are ready to go! Let's load the dataset into a Pandas dataframe:

df = pd.read_excel("Canada.xlsx")

In [ ]:
#df

Oh! Here we go again. Did your code encounter problems once more? So sad.

This time, you will read the error code and try to fix it by yourself. You know, I am old, and I will not be here forever.

In [ ]:
# If you can see the table below it means you had success! But what are all these NaN in the data?!
# Open the Canada.xlsx file and check it structure

df

It turns out that we actually have distinct sheets in our dataset: "Regions by Citizenship" and "Canada by Citizenship."

Let's focus on the "Canada by Citizenship" sheet. Take a look at it. What do you see in the first lines?

Yes, we still have a problem; the Excel file has a header (the blue part) that is not formatted in a tabular way. So, we need to get rid of it when loading the data. Otherwise, we will load the DataFrame in the wrong way.

Since you are looking at the data, try to look at the lines of the data. What do you see in the last two lines?

Yes, it has some data that are not following the dataset format as well. Let's get rid of these two lines as well.

*"DataFrame? What is this?" We will talk about that soon.*

In [ ]:
# Let's try to load the dataset again. But first, let's see what options the function provides to us.
# For this, let's use a feature provided by the notebook environment.
# We can see the parameters of a function in a Jupyter Notebook using the '?' symbol after the function name:

pd.read_excel?

# Check the signature below and try to find the parameter that will allow us to define the sheet name, skip some rows and skip the footer.

In [ ]:
# Great! You found it. Right? Riiight?
# Now let's load the dataset, given the sheet_name and the list of rows it should skip. And do not forget to skip the footers!

# TODO: Load the dataset
df  = pd.read_excel("Canada.xlsx", header=20, sheet_name="Canada by Citizenship")  # <--- complete the call

# Remove the comment from the line below to print the DataFrame
df.head(2)

In [ ]:
# To see the last lines in the dataset you can take a look at the tail
df.tail(3)

## Pandas Dataframes

In the line above, you created a Pandas DataFrame. A DataFrame is a two-dimensional and highly flexible data structure provided by Pandas. It is one of the most commonly used data structures for data manipulation and analysis in data science and data engineering.

Throughout this course, the DataFrame will be one of our main "data units." What does that mean? We will always handle the data by loading it into a DataFrame, and from there, we will use other libraries to generate all sorts of visualizations. Be friends with your DataFrames; they are very powerful and can be used not only in data visualization but also in data analysis. Let's explore a little bit of that in the sequence.

In [ ]:
# When working with a dataset, it's always good to start by checking the basic information about your dataframe.
# We can do that by using the info() method:

df.info(verbose=True)

The main types stored in Pandas are float, int, bool, datetime64[ns], datetime64[ns, tz], timedelta[ns], category, and object (string). 
In addition, these types have item sizes, e.g., int64 and int32.

**What are the types we have in this dataset?**

In [ ]:
# We can also see the size of the dataframe (rows, columns)
df.shape

In [ ]:
# Let's clean the dataset to remove a few unnecessary columns. We can use the pandas drop() method for that.

# First, let's create a list with the columns we want to drop.
columns = ['AREA', 'REG', 'DEV', 'Type', 'Coverage']

# Then, let's drop them.
# In pandas, axis=0 represents rows (default), and axis=1 represents columns.
df.drop(columns, axis=1, inplace=True)

# After cleaning it up, let's see the first 10 lines.
df.head(10)

In [ ]:
# The column names are not nice. Let's rename the columns so they can be as nice as we are.

# First, let's create a dictionary mapping the old names to the new coolest ones.
new_names = {'OdName': 'Country', 'AreaName': 'Continent', 'RegName': 'Region'}

# Now, let's rename the columns.
df.rename(columns=new_names, inplace=True)

In [28]:
# TODO: Check the names of the columns. Are they the new names?
df

,Country,Continent,Region,DevName,1980,1981,1982,1983,1984,1985,...,2005,2006,2007,2008,2009,2010,2011,2012,2013,Total
0,Afghanistan,Asia,Southern Asia,Developing regions,16,39,39,47,71,340,...,3436,3009,2652,2111,1746,1758,2203,2635,2004,58639
1,Albania,Europe,Southern Europe,Developed regions,1,0,0,0,0,0,...,1223,856,702,560,716,561,539,620,603,15699
2,Algeria,Africa,Northern Africa,Developing regions,80,67,71,69,63,44,...,3626,4807,3623,4005,5393,4752,4325,3774,4331,69439
3,American Samoa,Oceania,Polynesia,Developing regions,0,1,0,0,0,0,...,0,1,0,0,0,0,0,0,0,6
4,Andorra,Europe,Southern Europe,Developed regions,0,0,0,0,0,0,...,0,1,1,0,0,0,0,1,1,15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
192,Yemen,Asia,Western Asia,Developing regions,1,2,1,6,0,18,...,161,140,122,133,128,211,160,174,217,2985
193,Zambia,Africa,Eastern Africa,Developing regions,11,17,11,7,16,9,...,91,77,71,64,60,102,69,46,59,1677
194,Zimbabwe,Africa,Eastern Africa,Developing regions,72,114,102,44,32,29,...,615,454,663,611,508,494,434,437,407,8598
195,Unknown,World,World,World,44000,18078,16904,13635,14855,14368,...,4785,4583,4348,4197,3402,3731,2554,1681,1484,515059
196,Total,World,World,World,143137,128641,121175,89185,88272,84346,...,262242,251640,236753,247244,252170,280687,248748,257903,259021,6924212

As you can see, the number of immigrants is distributed over a range of years (from 1980 to 2013). It would be interesting to have a column with the total, wouldn't it?

Let's do it. Let's create a column called "Total" that sums up the total immigrants by country over the entire period.

But first, we need to create a list with all the years we want to sum up. We could do it like this: year_columns = ['1980', '1981', '1982', '1983', '1984', '1985', ...]

But there are 33 years!!! So let's be smart and create a function for that.

In [ ]:
# TODO: Finish the function below to create a list with all the years we have in the dataset.
# Note: the years are integers
def create_list(start, end):
    years_list = []  
    while start <= end:
        years_list.append(start)
        start = start + 1

    return years_list

year_columns = create_list(start=1980, end=2013)

# Check if the list has all the years we need.
print(year_columns)

In [ ]:
# Now that we have the list we finally can create the Total Column
df['Total'] = df[year_columns].sum(axis=1)

# Remember: 
# axis=0 would sum the values vertically, resulting in a single sum for each column.
# axis=1 sums the values horizontally, resulting in a sum for each row, which is what we want when creating a "Total" column for each row in a dataset.

df[df["Country"] == "Brazil"][["Country", "Total"]]

In [ ]:
# Check the Total column
df.head(20)

# Pandas Slicing


## Select Column

Did you see what we did in the previous cell? We indexed our DataFrame using the columns. This is called Slicing. 
We can generate subdatasets by selecting the columns we want.

There are two ways to filter by column name:

- Method 1: Very easy and intuitive, but only works for column names that do NOT have spaces or special characters. It will return a series (We will talk about that soon).
```python
    df.column_name               # returns a series
```
- Method 2: The one we used previously. It can filter on multiple columns.
```python
    df['column']                  # returns a series like df.column_name
    df[['column 1', 'column 2']]  # returns a DataFrame
```

In [ ]:
# Let's try fi 'ltering on the list of countries ('Country').
df.Country
#df[["Country", "Region"]]

            Country           Region
0       Afghanistan    Southern Asia
1           Albania  Southern Europe
2           Algeria  Northern Africa
3    American Samoa        Polynesia
4           Andorra  Southern Europe
..              ...              ...
192           Yemen     Western Asia
193          Zambia   Eastern Africa
194        Zimbabwe   Eastern Africa
195         Unknown            World
196           Total            World

[197 rows x 2 columns]

In [ ]:
# Now, let's filter the list of countries ('Country') and the data for the years: 1980 - 1985.

# TODO: Add the years.
df[['Country', 1980]]

# Selecting Rows

**WARNING: THIS IS A VERY IMPORTANT TOPIC!**

We can also select rows. There are different ways to do that:

1. Using `.loc[]` to select rows based on labels or conditions.
    ```python
    df.loc[row_label]  # Select a single row by its label
    df.loc[start_label:end_label]  # Select a range of rows by their labels
    df.loc[df['Column'] == 'Value']  # Select rows based on a condition
    ```
2. Using `.iloc[]` to select rows based on integer positions.
    ```python
    df.iloc[row_index]  # Select a single row by its integer position
    df.iloc[start_index:end_index]  # Select a range of rows by their integer positions
    ```

3. Using Conditions: You can filter rows based on conditions using boolean indexing.
    ```python
    df[df['Column'] == 'Value']  # Select rows where a specific condition is met
    ```
4. Using `.query()`: The `.query()` method allows you to filter rows using a query expression.
    ```python
    df.query('Column == "Value"')  # Select rows based on a query expression
    ```

In [ ]:
# Let's do it together!
# 1. How can we select the line of Japan?
# 2. How can we select the countries from Asia?
# 3. How can we select the countries from Asia that have fewer than 5K immigrants to Canada?
# 4. How can we select the row of 2011 for the countries from Asia that have fewer than 5k immigrants?

In [ ]:
# TODO: Using .loc[], Check the number of immigrants from France for the following scenarios:
# 1. The full row data (all columns)
# 2. For year 2000
# 3. For years 1990 to 1995

In [ ]:
# TODO: Check the data from Europe for two different regions: Western and Southern.

# Display the dataframe and find out how many instances (rows) are there for each one of the regions.

### Sorting Values of a DataFrame

The `sort_values()` function is used to sort a DataFrame or a Series based on one or more columns.

You have to specify one or more columns by which you want to sort and the order (ascending or descending).

```python
df.sort_values(col_name, axis=0, ascending=True, inplace=False, ignore_index=False)
```

- `col_name` - the column(s) to sort by.
- `axis` - axis along which to sort. 0 for sorting by rows (default) and 1 for sorting by columns.
- `ascending` - to sort in ascending order (True, default) or descending order (False).
- `inplace` - to perform the sorting operation in-place (True) or return a sorted copy (False, default).
- `ignore_index` - to reset the index after sorting (True) or keep the original index values (False, default).

In [ ]:
# Let's sort out the dataframe in descending order to find out the top 10 countries that has the most imigrations to Canada

df_sorted = df.sort_values("Total", ascending=False, axis=0, inplace=False)

In [ ]:
# TODO: Print the top 10 countries
#df_sorted

In [ ]:
# TODO: Find out top 3 countries that contributes the most to immigration to Canda in the year 1992.
# Display the country names with the immigrant count in this year