# Exercise 02 - Netflix Movies and TV Shows

Use markdown or comments to indicate exercise numbers. Fill each code cell with your solution.

In [92]:
# Optional setup cell
import pandas as pd
import numpy as np

## 1. Build Full DataFrame

Read all 14 CSV files from `exercise-02/dataset` and create **one** pandas DataFrame containing the full dataset (expected shape: 8800 rows, 12 columns).

In [93]:
from pathlib import Path

data_dir = Path("dataset")
csv_files = sorted(data_dir.glob("*.csv"))

df_full = pd.concat([pd.read_csv(file) for file in csv_files], ignore_index=True)
print("Shape:", df_full.shape)
df_full.head()

Shape: (8800, 12)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s108,Movie,A Champion Heart,David de Vos,"Mandy Grace, David de Vos, Donna Rusch, Devan ...",United States,"September 4, 2021",2018,G,90 min,"Children & Family Movies, Dramas",When a grieving teen must work off her debt to...
1,s934,Movie,Hachi: A Dog's Tale,Lasse Hallström,"Richard Gere, Joan Allen, Cary-Hiroyuki Tagawa...","United Kingdom, United States","May 1, 2021",2009,G,93 min,"Children & Family Movies, Dramas","When his master dies, a loyal pooch named Hach..."
2,s1127,Movie,My Fair Lady,George Cukor,"Audrey Hepburn, Rex Harrison, Stanley Holloway...",United States,"April 1, 2021",1964,G,173 min,"Classic Movies, Music & Musicals",When a Cockney flower girl takes elocution les...
3,s1558,Movie,Canvas,Frank E. Abney III,NaN,United States,"December 11, 2020",2020,G,9 min,"Children & Family Movies, Dramas","After a heartbreaking loss, a grandfather stru..."
4,s2912,Movie,A Shaun the Sheep Movie: Farmageddon,"Richard Phelan, Will Becher","Justin Fletcher, John Sparkes, Amalia Vitale, ...","United Kingdom, France, Belgium, Ireland, Unit...","February 14, 2020",2019,G,87 min,"Children & Family Movies, Comedies",Shaun and the flock race to help an adorable a...

## 2. Data Cleaning

Perform the cleaning procedures:
- (a) Check null values and identify the top 2 columns with most nulls.
- (b) Remove the 1st and 3rd columns with most null values using `drop`.
- (c) Replace all `NaN` in `country` with `"United States"`.
- (d) Drop `date_added` column.

In [94]:
# Write your solution here

#(a)
null_count = df_full.isnull().sum()
sorted_null = null_count.sort_values(ascending=False)
print(sorted_null.head(2))

#(b)
to_drop = [sorted_null.index[0], sorted_null.index[2]]
df_full.drop(columns = to_drop, inplace=True)

#(c)
df_full['country'] = df_full['country'].fillna('United States')

#(d)
df_full.drop(columns = ['date_added'], inplace=True)


df_full.head()

director    2631
country      830
dtype: int64

,show_id,type,title,country,release_year,rating,duration,listed_in,description
0,s108,Movie,A Champion Heart,United States,2018,G,90 min,"Children & Family Movies, Dramas",When a grieving teen must work off her debt to...
1,s934,Movie,Hachi: A Dog's Tale,"United Kingdom, United States",2009,G,93 min,"Children & Family Movies, Dramas","When his master dies, a loyal pooch named Hach..."
2,s1127,Movie,My Fair Lady,United States,1964,G,173 min,"Classic Movies, Music & Musicals",When a Cockney flower girl takes elocution les...
3,s1558,Movie,Canvas,United States,2020,G,9 min,"Children & Family Movies, Dramas","After a heartbreaking loss, a grandfather stru..."
4,s2912,Movie,A Shaun the Sheep Movie: Farmageddon,"United Kingdom, France, Belgium, Ireland, Unit...",2019,G,87 min,"Children & Family Movies, Comedies",Shaun and the flock race to help an adorable a...

## 3. Most Common Rating

From `rating`, find which rating has the highest number of releases and how many releases it has.

In [95]:
# Write your solution here
ratings_count = df_full['rating'].value_counts()
print(ratings_count.head(1))

rating
TV-MA    3207
Name: count, dtype: int64

## 4. Top 3 Genres

Find the top 3 motion picture genres with the most releases in the full dataset.

In [96]:
# Write your solution here
most_common_genre = df_full['listed_in'].value_counts()
print(most_common_genre)

listed_in
Dramas, International Movies                          362
Documentaries                                         359
Stand-Up Comedy                                       334
Comedies, Dramas, International Movies                274
Dramas, Independent Movies, International Movies      252
                                                     ...
British TV Shows, Classic & Cult TV, Kids' TV           1
Anime Series, Kids' TV, TV Action & Adventure           1
Classic & Cult TV, Kids' TV, TV Action & Adventure      1
Children & Family Movies, Comedies, LGBTQ Movies        1
Crime TV Shows, Kids' TV                                1
Name: count, Length: 514, dtype: int64

## 5. Action & Adventure Percentage

Compute the percentage of releases listed as `Action & Adventure` in the full dataset.

In [106]:
# Write your solution here
Action = df_full['listed_in'].str.contains("Action & Adventure").sum()
print(f"{Action/ len(df_full) * 100 :.2f} %")

11.67 %

## 6. Movies vs TV Shows (Counts)

Determine whether there are more Movies or TV Shows and report both counts.

In [98]:
# Write your solution here
typeCount = df_full['type'].value_counts()
print(typeCount)

type
Movie      6126
TV Show    2674
Name: count, dtype: int64

## 7. Movies vs TV Shows (Percentages)

Compute the percentage of Movies and TV Shows in the full dataset.

In [99]:
# Write your solution here
print(f"Movies: {typeCount['Movie']/ len(df_full) * 100 :.2f} %")
print(f"TV Shows: {typeCount['TV Show']/ len(df_full) * 100 :.2f} %")

Movies: 69.61 %
TV Shows: 30.39 %

## 8. Top 5 Years

Find the top 5 years with the most releases.

In [100]:
# Write your solution here
release_count = df_full['release_year'].value_counts()
print(release_count.head(5))

release_year
2018    1147
2019    1030
2017    1030
2020     953
2016     902
Name: count, dtype: int64

## 9. Oldest Stand-Up Comedy in US

Print the first 10 oldest `Stand-Up Comedy` releases in the United States.

In [107]:
# Write your solution here
stand_up_us = df_full[
    (df_full['listed_in'].str.contains("Stand-Up")) &
    (df_full['country'] == "United States")
]
oldest_stand_up = stand_up_us.sort_values('release_year').head(10)
print(oldest_stand_up[['title', 'release_year']])

                                       title  release_year
6477          Richard Pryor: Live in Concert          1979
6795                 Eddie Murphy: Delirious          1983
5771         Sam Kinison: Breaking the Rules          1987
1074                       Eddie Murphy: Raw          1987
5767                    Bill Hicks: Sane Man          1989
5775                 Tim Allen: Men Are Pigs          1990
5776              Tim Allen: ReWires America          1991
5772  Sam Kinison: Family Entertainment Hour          1991
5773              Sam Kinison: Live in Vegas          1991
1378         Denis Leary: No Cure For Cancer          1992

## 10. First Kids' TV Release

Find when the first `Kids' TV` show was released.

In [102]:
# Write your solution here
Kids_TV = df_full[(df_full['listed_in'].str.contains("Kids' TV"))]
Kids_TV = Kids_TV.sort_values('release_year')
first_Show = Kids_TV.head(1)
print(first_Show[['title', 'release_year']])

         title  release_year
7881  El Chavo          1979

## 11. Top 5 Countries

Find the top 5 countries with the most releases in the dataset.

In [103]:
# Write your solution here
release_count = df_full['country'].value_counts()
print(release_count.head(5))

country
United States     3645
India              972
United Kingdom     419
Japan              244
South Korea        199
Name: count, dtype: int64

## 12. Movies-Only DataFrame

Create a Movies-only DataFrame and answer:
- (a) Number of rows
- (b) Percentage of movies in each rating
- (c) Top 10 movie genres
- (d) Year with most movie releases
- (e) Top 15 oldest movies available on Netflix

In [104]:
# Write your solution here
# (a)
df_movies = df_full[df_full['type'] == 'Movie']
print(f"num of movies: {len(df_movies)}")

# (b)
percent_ratings = ((df_movies["rating"].value_counts(normalize=True) * 100).round(2).astype(str)+ " %")
print(percent_ratings )

# (c)
genre_count = df_movies['listed_in'].value_counts()
print(genre_count.head(10))

# (d)
year_count = df_movies['release_year'].value_counts()
print(year_count.head(10))

# (e)
oldest_movies = df_movies.sort_values('release_year')
print(oldest_movies.head(15))

num of movies: 6126
rating
TV-MA       33.66 %
TV-14       23.29 %
R           13.01 %
TV-PG        8.81 %
PG-13         8.0 %
PG           4.68 %
TV-Y7        2.27 %
TV-Y         2.14 %
TV-G         2.06 %
NR           1.22 %
G            0.67 %
TV-Y7-FV     0.08 %
NC-17        0.05 %
UR           0.05 %
Name: proportion, dtype: str
listed_in
Dramas, International Movies                        362
Documentaries                                       359
Stand-Up Comedy                                     334
Comedies, Dramas, International Movies              274
Dramas, Independent Movies, International Movies    252
Children & Family Movies                            215
Children & Family Movies, Comedies                  201
Documentaries, International Movies                 186
Dramas, International Movies, Romantic Movies       180
Comedies, International Movies                      176
Name: count, dtype: int64
release_year
2018    767
2017    765
2016    658
2019    633
2020    517
2015    396
2021    277
2014    264
2013    225
2012    173
Name: count, dtype: int64
     show_id   type                                             title  \
3644   s7791  Movie                                    Prelude to War
3732   s8206  Movie                              The Battle of Midway
8129   s8661  Movie     Undercover: How to Operate Behind Enemy Lines
8135   s8740  Movie                Why We Fight: The Battle of Russia
8140   s8764  Movie                   WWII: Report from the Aleutians
8110   s8420  Movie  The Memphis Belle: A Story of a\nFlying Fortress
3819   s8641  Movie                                  Tunisian Victory
3773   s8437  Movie                                 The Negro Soldier
3522   s7220  Movie                           Know Your Enemy - Japan
3684   s7931  Movie                                        San Pietro
6988   s7576  Movie                          Nazi Concentration Camps
7956   s7295  Movie                                Let There Be Light
8125   s8588  Movie                                       Thunderbolt
3915   s1700  Movie                                   White Christmas
2244   s2376  Movie                                   The Blazing Sun

                            country  release_year rating duration  \
3644                  United States          1942  TV-14   52 min
3732                  United States          1942  TV-14   18 min
8129                  United States          1943  TV-PG   61 min
8135                  United States          1943  TV-PG   82 min
8140                  United States          1943  TV-PG   45 min
8110                  United States          1944  TV-PG   40 min
3819  United States, United Kingdom          1944  TV-14   76 min
3773                  United States          1944  TV-14   40 min
3522                  United States          1945  TV-14   63 min
3684                  United States          1945  TV-14   32 min
6988                  United States          1945  TV-MA   59 min
7956                  United States          1946  TV-PG   58 min
8125                  United States          1947  TV-PG   42 min
3915                  United States          1954   TV-G  120 min
2244                          Egypt          1954  TV-14  116 min

                                              listed_in  \
3644                      Classic Movies, Documentaries
3732                      Classic Movies, Documentaries
8129                      Classic Movies, Documentaries
8135                                      Documentaries
8140                                      Documentaries
8110                      Classic Movies, Documentaries
3819                      Classic Movies, Documentaries
3773                      Classic Movies, Documentaries
3522                      Classic Movies, Documentaries
3684                      Classic Movies, Documentaries
6988                      Classic Movies, Documentaries
7956                      Classic Movies, Documentaries
8125                      Classic Movies, Documentaries
3915  Children & Family Movies, Classic Movies, Come...
2244       Classic Movies, Dramas, International Movies

                                            description
3644  Frank Capra's documentary chronicles the rise ...
3732  Director John Ford captures combat footage of ...
8129  This World War II-era training film dramatizes...
8135  This installment of Frank Capra's acclaimed do...
8140  Filmmaker John Huston narrates this Oscar-nomi...
8110  This documentary centers on the crew of the B-...
3819  British and American troops join forces to lib...
3773  This documentary urged African Americans to en...
3522  Though culturally insensitive by modern standa...
3684  After the Allies invade Italy, the Liri Valley...
6988  Shocking footage shows Nazi concentration camp...
7956  Some returning combat veterans suffer scars th...
8125  A P-47 Thunderbolt squadron is shown in prepar...
3915  Two war buddies fall for two sisters and follo...
2244  Competition between sugar cane producers turns...

## 13. TV Shows-Only DataFrame

Create a TV Shows-only DataFrame and answer:
- (a) Number of rows
- (b) Percentage of TV shows in each rating
- (c) Top 10 TV show genres
- (d) Year with most TV show releases
- (e) Top 15 oldest TV shows available on Netflix

In [105]:
# Write your solution here
# (a)
df_shows = df_full[df_full['type'] == 'TV Show']
print(f"num of shows: {len(df_shows)}")

# (b)
percent_ratings = ((df_shows["rating"].value_counts(normalize=True) * 100).round(2).astype(str)+ " %")
print(percent_ratings )

# (c)
genre_count = df_shows['listed_in'].value_counts()
print(genre_count.head(10))

# (d)
year_count = df_shows['release_year'].value_counts()
print(year_count.head(10))

# (e)
oldest_shows = df_shows.sort_values('release_year')
print(oldest_shows.head(15))

num of shows: 2674
rating
TV-MA       42.82 %
TV-14       27.41 %
TV-PG       12.08 %
TV-Y7        7.29 %
TV-Y         6.58 %
TV-G         3.52 %
NR           0.19 %
R            0.07 %
TV-Y7-FV     0.04 %
Name: proportion, dtype: str
listed_in
Kids' TV                                                  220
International TV Shows, TV Dramas                         121
Crime TV Shows, International TV Shows, TV Dramas         110
Kids' TV, TV Comedies                                      98
Reality TV                                                 95
International TV Shows, Romantic TV Shows, TV Comedies     94
International TV Shows, Romantic TV Shows, TV Dramas       90
Anime Series, International TV Shows                       87
Docuseries                                                 85
TV Comedies                                                69
Name: count, dtype: int64
release_year
2020    436
2019    397
2018    380
2021    315
2017    265
2016    244
2015    161
2014     88
2012     64
2013     62
Name: count, dtype: int64
     show_id     type                                title  \
2750   s4251  TV Show    Pioneers: First Women Filmmakers*
4526   s1332  TV Show  Five Came Back: The Reference Films
3639   s7744  TV Show  Pioneers of African-American Cinema
3794   s8542  TV Show  The Twilight Zone (Original Series)
4068   s8190  TV Show               The Andy Griffith Show
5919   s4551  TV Show     Monty Python's Fliegender Zirkus
2832   s4552  TV Show         Monty Python's Flying Circus
7865   s6550  TV Show                           Dad's Army
7881   s6675  TV Show                             El Chavo
8744   s7589  TV Show                        Ninja Hattori
7065   s7879  TV Show                             Robotech
3699   s7994  TV Show                           Shaka Zulu
2368   s2741  TV Show                          Saint Seiya
7747   s5300  TV Show                            High Risk
7923   s6971  TV Show                    Highway to Heaven

                                                country  release_year rating  \
2750                                      United States          1925  TV-14
4526                                      United States          1945  TV-MA
3639                                      United States          1946  TV-14
3794                                      United States          1963  TV-14
4068                                      United States          1967   TV-G
5919                       United Kingdom, West Germany          1972  TV-MA
2832                                     United Kingdom          1974  TV-14
7865                                     United Kingdom          1977  TV-PG
7881                                             Mexico          1979  TV-PG
8744                                              Japan          1981  TV-Y7
7065                               United States, Japan          1985  TV-MA
3699  Italy, South Africa, West Germany, Australia, ...          1986  TV-14
2368                                              Japan          1986  TV-14
7747                                      United States          1988  TV-PG
7923                                      United States          1988  TV-PG

        duration                                          listed_in  \
2750    1 Season                                           TV Shows
4526    1 Season                                           TV Shows
3639    1 Season                                           TV Shows
3794   4 Seasons             Classic & Cult TV, TV Sci-Fi & Fantasy
4068   8 Seasons                     Classic & Cult TV, TV Comedies
5919    1 Season                International TV Shows, TV Comedies
2832   4 Seasons  British TV Shows, Classic & Cult TV, Internati...
7865  10 Seasons   British TV Shows, Classic & Cult TV, TV Comedies
7881    1 Season  Classic & Cult TV, Kids' TV, Spanish-Language ...
8744    1 Season                             Anime Series, Kids' TV
7065    1 Season                                       Anime Series
3699    1 Season                                          TV Dramas
2368   6 Seasons                                       Anime Series
7747    1 Season                             Docuseries, Reality TV
7923   5 Seasons                                          TV Dramas

                                            description
2750  This collection restores films from women who ...
4526  This collection includes 12 World War II-era p...
3639  This newly preserved collection features more ...
3794  Hosted by creator Rod Serling, this groundbrea...
4068  Homespun humor and easygoing Sheriff Andy Tayl...
5919  The Pythons elevate the absurd to new heights ...
2832  The Monty Python players make their mark with ...
7865  This beloved sitcom follows the unlikely heroe...
7881  El Chavo is a poor, nameless orphan who lives ...
8744  Elementary school student Kenichi Mitsuba's ho...
7065  When a mysterious spaceship crashes in the Pac...
3699  This miniseries recounts the early 19th-centur...
2368  A band of young warriors in magical armor vow ...
7747  From scientists to snake handlers, this series...
7923  Under God's direction, angel Jonathan and ex-c...