# Exercises 03


This notebook contains the answers to Exercise 03 – Netflix

## Exercise 1

Read all the files and create ONE pandas DataFrame containing the full dataset. (The full
dataset is supposed to have 12 columns and 8800 rows.)

In [1]:
import pandas as pd


df_g = pd.read_csv("dataset/netflix_titles_G.csv")
df_nc = pd.read_csv("dataset/netflix_titles_NC-17.csv")
df_nr = pd.read_csv("dataset/netflix_titles_NR.csv")
df_pg13 = pd.read_csv("dataset/netflix_titles_PG-13.csv")
df_pg = pd.read_csv("dataset/netflix_titles_PG.csv")
df_r = pd.read_csv("dataset/netflix_titles_R.csv")
df_tv14 = pd.read_csv("dataset/netflix_titles_TV-14.csv")
df_tvg = pd.read_csv("dataset/netflix_titles_TV-G.csv")
df_tvma = pd.read_csv("dataset/netflix_titles_TV-MA.csv")
df_tvpg = pd.read_csv("dataset/netflix_titles_TV-PG.csv")
df_tvy = pd.read_csv("dataset/netflix_titles_TV-Y.csv")
df_tvy7fv = pd.read_csv("dataset/netflix_titles_TV-Y7-FV.csv")
df_tvy7 = pd.read_csv("dataset/netflix_titles_TV-Y7.csv")
df_ur = pd.read_csv("dataset/netflix_titles_UR.csv")

df = pd.concat([df_g, df_nc, df_nr, df_pg13, df_pg, df_r, df_tv14, df_tvg,
                df_tvma, df_tvpg, df_tvy, df_tvy7fv, df_tvy7, df_ur], ignore_index=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8800 entries, 0 to 8799
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8800 non-null   object
 1   type          8800 non-null   object
 2   title         8800 non-null   object
 3   director      6169 non-null   object
 4   cast          7975 non-null   object
 5   country       7970 non-null   object
 6   date_added    8790 non-null   object
 7   release_year  8800 non-null   int64
 8   rating        8800 non-null   object
 9   duration      8800 non-null   object
 10  listed_in     8800 non-null   object
 11  description   8800 non-null   object
dtypes: int64(1), object(11)
memory usage: 825.1+ KB

## Exercise 2 - Data Cleaning

In [2]:
# a.​ Check for null values in your data. What are the top TWO columns with the most null values?
df.isnull().sum()

# director : 2631 null values
# country : 830 null values
# cast : 825 null values

show_id            0
type               0
title              0
director        2631
cast             825
country          830
date_added        10
release_year       0
rating             0
duration           0
listed_in          0
description        0
dtype: int64

In [3]:
# b. Remove the first and the third column with the most null values from your data using the drop procedure.

columns_to_drop = ['director', 'cast']
df = df.drop(columns=columns_to_drop)
df.head()

,show_id,type,title,country,date_added,release_year,rating,duration,listed_in,description
0,s108,Movie,A Champion Heart,United States,"September 4, 2021",2018,G,90 min,"Children & Family Movies, Dramas",When a grieving teen must work off her debt to...
1,s934,Movie,Hachi: A Dog's Tale,"United Kingdom, United States","May 1, 2021",2009,G,93 min,"Children & Family Movies, Dramas","When his master dies, a loyal pooch named Hach..."
2,s1127,Movie,My Fair Lady,United States,"April 1, 2021",1964,G,173 min,"Classic Movies, Music & Musicals",When a Cockney flower girl takes elocution les...
3,s1558,Movie,Canvas,United States,"December 11, 2020",2020,G,9 min,"Children & Family Movies, Dramas","After a heartbreaking loss, a grandfather stru..."
4,s2912,Movie,A Shaun the Sheep Movie: Farmageddon,"United Kingdom, France, Belgium, Ireland, Unit...","February 14, 2020",2019,G,87 min,"Children & Family Movies, Comedies",Shaun and the flock race to help an adorable a...

In [4]:
# c.  The country column has the second most null values. Handle it: Replace all the NaN values in the country column with "United States", as Netflix was created inthe USA and every show is aired on Netflix US.

df['country'] = df['country'].fillna('United States')
df.isnull().sum()

show_id          0
type             0
title            0
country          0
date_added      10
release_year     0
rating           0
duration         0
listed_in        0
description      0
dtype: int64

In [5]:
# c.  Since we already have the release year for each movie, we can drop the date_added column. Drop the date_added column.

df = df.drop(columns=['date_added'])
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8800 entries, 0 to 8799
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8800 non-null   object
 1   type          8800 non-null   object
 2   title         8800 non-null   object
 3   country       8800 non-null   object
 4   release_year  8800 non-null   int64
 5   rating        8800 non-null   object
 6   duration      8800 non-null   object
 7   listed_in     8800 non-null   object
 8   description   8800 non-null   object
dtypes: int64(1), object(8)
memory usage: 618.9+ KB

## Exercise 3

Looking at the motion picture rating (column rating), what is the rating with the most
number of releases? How many are there?

In [6]:
display(df.groupby('rating').size().reset_index(name='counts').sort_values(by='counts', ascending=False))
print("Rating 'TV-MA' has the most counts with  3207")

      rating  counts
8      TV-MA    3207
6      TV-14    2160
9      TV-PG     863
5          R     799
4      PG-13     490
11     TV-Y7     334
10      TV-Y     307
3         PG     287
7       TV-G     220
2         NR      80
0          G      41
12  TV-Y7-FV       6
1      NC-17       3
13        UR       3

Rating 'TV-MA' has the most counts with  3207

## Exercise 4
What are the top three motion picture genres with the most releases in this dataset?

In [7]:
display(df.groupby('listed_in').size().reset_index(name='counts').sort_values(by='counts', ascending=False).head(3))
print("The most common genre is 'Dramas, International Movies' with  362 counts")
print("The second most common genre is 'Documentaries' with  359 counts")
print("The third most common genre is 'Stand-Up Comedy	' with  334 counts")

                        listed_in  counts
326  Dramas, International Movies     362
274                 Documentaries     359
470               Stand-Up Comedy     334

The most common genre is 'Dramas, International Movies' with  362 counts
The second most common genre is 'Documentaries' with  359 counts
The third most common genre is 'Stand-Up Comedy	' with  334 counts

## Exercise 5
Considering the full dataset, what is the percentage of releases that are listed as “Action
& Adventure”?

In [8]:
total_entries = len(df)
df_action_adventure = df[df['listed_in'] == 'Action & Adventure']
total_action_adventure = len(df_action_adventure)

print(f"Total entries: {total_entries}")
print(f"Total entries in Action & Adventure: {total_action_adventure}")
print(f"Percentage of Action & Adventure: {total_action_adventure / total_entries * 100:.2f}%")

Total entries: 8800
Total entries in Action & Adventure: 128
Percentage of Action & Adventure: 1.45%

## Exercise 6
Are there more movies or TV shows in the dataset? How many movies and how many
TV shows are there?

In [9]:
df_movie = df[df['type'] == 'Movie']
df_tvshow = df[df['type'] == 'TV Show']

print(f"Total entries in Movies: {len(df_movie)}")
print(f"Total entries in TV Shows: {len(df_tvshow)}")
print(f"There are more movies than TV shows in the dataset")

Total entries in Movies: 6126
Total entries in TV Shows: 2674
There are more movies than TV shows in the dataset

## Exercise 7
Considering the full dataset, what are the percentages of movies and TV shows?

In [10]:
total_dataset = len(df)
total_movies = len(df_movie)    
total_tvshows = len(df_tvshow)

print(f"Total entries in the dataset: {total_dataset}")
print(f"Total entries in Movies: {total_movies}")
print(f"Total entries in TV Shows: {total_tvshows}")
print(f"Percentage of Movies: {total_movies / total_dataset * 100:.2f}%")
print(f"Percentage of TV Shows: {total_tvshows / total_dataset * 100:.2f}%")

Total entries in the dataset: 8800
Total entries in Movies: 6126
Total entries in TV Shows: 2674
Percentage of Movies: 69.61%
Percentage of TV Shows: 30.39%

## Exercise 8
What are the top 5 years with the most releases?

In [11]:
df.groupby('release_year').size().reset_index(name='counts').sort_values(by='counts', ascending=False).head(5)

    release_year  counts
70          2018    1147
69          2017    1030
71          2019    1030
72          2020     953
68          2016     902

## Exercise 9
Print the first 10 oldest “Stand-Up Comedy” releases in the United States.

In [12]:
df[df['listed_in'] == "Stand-Up Comedy"].sort_values(by='release_year', ascending=True).head(10)[['title', 'release_year', 'listed_in']]

                                       title  release_year        listed_in
6477          Richard Pryor: Live in Concert          1979  Stand-Up Comedy
6795                 Eddie Murphy: Delirious          1983  Stand-Up Comedy
5771         Sam Kinison: Breaking the Rules          1987  Stand-Up Comedy
1074                       Eddie Murphy: Raw          1987  Stand-Up Comedy
5767                    Bill Hicks: Sane Man          1989  Stand-Up Comedy
5775                 Tim Allen: Men Are Pigs          1990  Stand-Up Comedy
5763             Bill Hicks: One Night Stand          1991  Stand-Up Comedy
5773              Sam Kinison: Live in Vegas          1991  Stand-Up Comedy
5776              Tim Allen: ReWires America          1991  Stand-Up Comedy
5772  Sam Kinison: Family Entertainment Hour          1991  Stand-Up Comedy

## Exercise 10
When was the first “Kids' TV” show released?

In [13]:
df[(df['listed_in'] == "Kids' TV") & (df['type'] == 'TV Show')].sort_values(by='release_year', ascending=True).head(1)[['title', 'type', 'release_year', 'listed_in']]

print("The first Kids' TV show is 'The super Mario Bros. super Show!' released in 1989")

The first Kids' TV show is 'The super Mario Bros. super Show!' released in 1989

## Exercise 11
​What are the top 5 countries with the most releases in this dataset?

In [14]:
    df['country'].value_counts().head(5)

country
United States     3645
India              972
United Kingdom     419
Japan              244
South Korea        199
Name: count, dtype: int64

## Exercise 12 - Movies Analysis
Create a dataframe with only the Movies and answer the following questions:

In [15]:
df_movies = df[df['type'] == "Movie"]

In [16]:
# a.​ How many rows does the Movies dataframe have?
print(f"The Movies dataframe has {len(df_movies)} rows.")

The Movies dataframe has 6126 rows.

In [17]:
# b. Considering the total number of MOVIES in the dataset, what is the percentage of movies in each rating?
gb = df_movies.groupby('rating')

for name, group in gb:
    percentage = len(group) / len(df_movies) * 100
    print(f"Rating {name}: {percentage:.2f}%")

Rating G: 0.67%
Rating NC-17: 0.05%
Rating NR: 1.22%
Rating PG: 4.68%
Rating PG-13: 8.00%
Rating R: 13.01%
Rating TV-14: 23.29%
Rating TV-G: 2.06%
Rating TV-MA: 33.66%
Rating TV-PG: 8.81%
Rating TV-Y: 2.14%
Rating TV-Y7: 2.27%
Rating TV-Y7-FV: 0.08%
Rating UR: 0.05%

In [18]:
# C.  What are the top 10 genres of movies?

df_movies['listed_in'].value_counts().head(10)

listed_in
Dramas, International Movies                        362
Documentaries                                       359
Stand-Up Comedy                                     334
Comedies, Dramas, International Movies              274
Dramas, Independent Movies, International Movies    252
Children & Family Movies                            215
Children & Family Movies, Comedies                  201
Documentaries, International Movies                 186
Dramas, International Movies, Romantic Movies       180
Comedies, International Movies                      176
Name: count, dtype: int64

In [19]:
# D. What is the year when the most MOVIES were released?

df_movies['release_year'].value_counts().head(1)

release_year
2018    767
Name: count, dtype: int64

In [20]:
# e; Print the top 15 oldest movies available on Netflix.

df_movies.sort_values(by='release_year', ascending=True).head(15)[['title', 'release_year', 'listed_in']]

,title,release_year,listed_in
3644,Prelude to War,1942,"Classic Movies, Documentaries"
3732,The Battle of Midway,1942,"Classic Movies, Documentaries"
8135,Why We Fight: The Battle of Russia,1943,Documentaries
8129,Undercover: How to Operate Behind Enemy Lines,1943,"Classic Movies, Documentaries"
8140,WWII: Report from the Aleutians,1943,Documentaries
8110,The Memphis Belle: A Story of a\nFlying Fortress,1944,"Classic Movies, Documentaries"
3819,Tunisian Victory,1944,"Classic Movies, Documentaries"
3773,The Negro Soldier,1944,"Classic Movies, Documentaries"
3522,Know Your Enemy - Japan,1945,"Classic Movies, Documentaries"
6988,Nazi Concentration Camps,1945,"Classic Movies, Documentaries"
3684,San Pietro,1945,"Classic Movies, Documentaries"
7956,Let There Be Light,1946,"Classic Movies, Documentaries"
8125,Thunderbolt,1947,"Classic Movies, Documentaries"
3915,White Christmas,1954,"Children & Family Movies, Classic Movies, Come..."
2244,The Blazing Sun,1954,"Classic Movies, Dramas, International Movies"

## Exercise 13 - TV Shows Analysis
Create a dataframe with only the TV Shows and answer the following questions:

In [21]:
df_tvshow = df[df['type'] == "TV Show"]

In [22]:
# a How many rows does the TV Shows dataframe have?

print(f"The TV Shows dataframe has {len(df_tvshow)} rows.")

The TV Shows dataframe has 2674 rows.

In [23]:
# b. Considering the total number of TV SHOWS in the dataset, what is the percentage of tv shows in each rating?

gb = df_tvshow.groupby('rating')
for name, group in gb:
    percentage = len(group) / len(df_tvshow) * 100
    print(f"Rating {name}: {percentage:.2f}%")

Rating NR: 0.19%
Rating R: 0.07%
Rating TV-14: 27.41%
Rating TV-G: 3.52%
Rating TV-MA: 42.82%
Rating TV-PG: 12.08%
Rating TV-Y: 6.58%
Rating TV-Y7: 7.29%
Rating TV-Y7-FV: 0.04%

In [24]:
# c. what are the top 10 genres of TV shows?

df_tvshow['listed_in'].value_counts().head(10)

listed_in
Kids' TV                                                  220
International TV Shows, TV Dramas                         121
Crime TV Shows, International TV Shows, TV Dramas         110
Kids' TV, TV Comedies                                      98
Reality TV                                                 95
International TV Shows, Romantic TV Shows, TV Comedies     94
International TV Shows, Romantic TV Shows, TV Dramas       90
Anime Series, International TV Shows                       87
Docuseries                                                 85
TV Comedies                                                69
Name: count, dtype: int64

In [25]:
# d  What is the year when the most TV SHOWS were released?

df_tvshow['release_year'].value_counts().head(1)

release_year
2020    436
Name: count, dtype: int64

In [26]:
# e.  Print the top 15 oldest movies available on Netflix.

df_tvshow.sort_values(by='release_year', ascending=True).head(15)[['title', 'release_year', 'listed_in']]

,title,release_year,listed_in
2750,Pioneers: First Women Filmmakers*,1925,TV Shows
4526,Five Came Back: The Reference Films,1945,TV Shows
3639,Pioneers of African-American Cinema,1946,TV Shows
3794,The Twilight Zone (Original Series),1963,"Classic & Cult TV, TV Sci-Fi & Fantasy"
4068,The Andy Griffith Show,1967,"Classic & Cult TV, TV Comedies"
5919,Monty Python's Fliegender Zirkus,1972,"International TV Shows, TV Comedies"
2832,Monty Python's Flying Circus,1974,"British TV Shows, Classic & Cult TV, Internati..."
7865,Dad's Army,1977,"British TV Shows, Classic & Cult TV, TV Comedies"
7881,El Chavo,1979,"Classic & Cult TV, Kids' TV, Spanish-Language ..."
8744,Ninja Hattori,1981,"Anime Series, Kids' TV"
7065,Robotech,1985,Anime Series
2368,Saint Seiya,1986,Anime Series
3699,Shaka Zulu,1986,TV Dramas
7923,Highway to Heaven,1988,TV Dramas
7747,High Risk,1988,"Docuseries, Reality TV"